# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95861768d91eddc5f38e51c14c2a134b812f86c8c7a9412ade9f0efe0f04fb0fc538d0a4345653fe5848045f96cc1ab92e35e285e3ca1bc180e8e267d8f8de45

test:
  secret_key_base: d258bf520fb14463941d363b156a05d7e2389fda6db845fe994a265704b7f4522574e4502bd6b07ed6402f70952e8a300a3e1beff6fc9e721f4d3b07647f89f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
